/// Flutter icons Harvyst
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Harvyst
///      fonts:
///       - asset: fonts/Harvyst.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Harvyst {
  Harvyst._();

  static const _kFontFam = 'Harvyst';
  static const String _kFontPkg = null;

  static const IconData couple = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_porn_folder__2_ = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData love = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
